[project]
name = "mcp-client-fastapi-agentsdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "mcp>=1.12.3",
    "openai-agents>=0.2.8",
    "streamlit>=1.48.1",
    "tavily-python>=0.7.11",
]
